# Generated by Django 5.1.6 on 2025-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
