# Generated by Django 5.1.6 on 2025-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_complaint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
