# Generated by Django 5.2.1 on 2025-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_complaint_budget_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('rejection', 'Rejection'), ('budget_update', 'Budget Update'), ('completion_update', 'Completion Update'), ('deletion', 'Deletion')], max_length=20),
        ),
    ]
